apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: foos.tools.example.com
spec:
  group: tools.example.com
  names:
    kind: Foo
    plural: foos
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            deploymentName:
              type: string
            replicas:
              format: int32
              type: integer
          required:
          - deploymentName
          - replicas
          type: object
        status:
          properties:
            availableReplicas:
              format: int32
              type: integer
          required:
          - availableReplicas
          type: object
  version: v1beta1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
